### PR TITLE
Use a conditional dependency for singledispatch

### LINKED ISSUE #182: singledispatch is not necessary for python_version >= Python3.4
I am using Python 3.7 and the attempt to install singledispatch is causing my build to break. I believe the way to resolve this issue is by using [conditional dependencies](https://hynek.me/articles/conditional-python-dependencies/) as outlined in [PEP 508](https://www.python.org/dev/peps/pep-0508/). I will follow up with a PR shortly.

### PR DESCRIPTION
**Pull request by smfoote**
I am not very familiar with conditional dependencies in Python, so please let me know if that is not the right way to handle this.

Fixes #182

### CODE REVIEW

**Comment by Nabellaleen** [comment]
Please check my question on #182 ;)

If your answer shows the conditional dependencie is required, you should also write a conditional import in `graphene_sqlalchemy/converter.py`, as the `singledispatch` in the standard library should be import with : `from functools import singledispatch`

```
try:
    from functools import singledispatch
except ImportError:
    from singledispatch import singledispatch
```

**Comment by dsully** [comment]
Would love to see this change updated, pushed and a release made. Our internal build system excludes "singledispatch" from our dependency tree as we are Python 3-only.

Thanks!

**Comment by JBrVJxsc** [comment]
having the same problem here. cannot believe this is not fixed after 2 years...

**Comment by erikwrede** [comment]
This is resolved in 3.0-Beta. The singledispatch dependency was removed since support for python < 3.6 was dropped.
If you require additional changes to be made, please open a new PR.

**Pull request closed without merging**
