### PR TITLE
Pick up the docstrings of hybrid properties

### PR DESCRIPTION
**Pull request by bim9262**
Use the docstring of hybrid properties as the description.

### CODE REVIEW

**Comment by bim9262** [comment]
The tox.ini and setup.py's sqlalchemy version requirements are at odds:

```
ERROR:   py37-sql11: could not install deps [.[test], sqlalchemy>=1.1,<1.2]; v = InvocationError("/tmp/graphene-sqlalchemy/.tox/py37-sql11/bin/python -m pip install '.[test]' 'sqlalchemy>=1.1,<1.2'", 1)
```

**Comment by bim9262** [comment]
Bumped build requirments for sqlalchemy becase as noted in the
documentation before version 1.3.19 the ordering for
all_orm_descriptors was not deterministic:
    
```
.. versionchanged:: 1.3.19 ensured deterministic ordering for
   :meth:`_orm.Mapper.all_orm_descriptors`.
```

**Review by erikwrede — COMMENTED** [review]
I think dropping support of SQA < 1.3.19 is critical and should be avoided. Is there a way to add this without dropping support for two major releases of SQLAlchemy?

**Comment by bim9262** [comment]
@erikwrede, I haven't been keeping up with developments in this project or SQA. What version of SQA should be targeted? It looks like the master branch still requires SQLAlchemy>=1.1,<2

**Comment by bim9262** [comment]
@erikwrede , I'll take a look. It's been a while since I've looked at this... Looks like some rebasing is in order too.

**Pull request closed without merging**
